version: "3.9"
services:
  miner_server:
    container_name: miner_server
    build:
      context: ./
      dockerfile: docker/miner/server/Dockerfile
    image: miner_server
    ports:
      - 65535:65535
    volumes:
      - ./bin:/root/ramium/bin
      - ./data:/root/ramium/data
      - ./include:/root/ramium/include
      - ./refs:/root/ramium/refs
      - ./scripts:/root/ramium/scripts
      - ./src:/root/ramium/src
      - ./tests:/root/ramium/tests
  miner_client:
    container_name: miner_client
    build:
      context: ./
      dockerfile: docker/miner/client/Dockerfile
    image: miner_client
    volumes:
      - ./bin:/root/ramium/bin
      - ./data:/root/ramium/data
      - ./include:/root/ramium/include
      - ./refs:/root/ramium/refs
      - ./scripts:/root/ramium/scripts
      - ./src:/root/ramium/src
      - ./tests:/root/ramium/tests